server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
